### ISSUE TITLE
Check on BufWritePost

### ISSUE THREAD

**Issue by mystilleef** [dgagn/diagflow.nvim#11]
Diagnostics don't seem to be correctly refreshed even after they've been addressed. After saving the document, can you trigger a check to clear the diagnostics properly? Relying on `CursorMoved` and `DiagnosticChanged` doesn't seem to be enough.

**Comment by dgagn** [comment]
Alright, I added a configuration option called `update_event` that must be a table containing the events to update the cached diagnostics.

```lua
-- lazy.nvim
  {
    'dgagn/diagflow.nvim',
    opts = {
      update_event = { 'DiagnosticChanged', 'BufWritePost' } -- anything can go there
    },
  }
```

I noticed that `intelephense` lsp is not giving the col, so putting the `scope` option to `line` can show everything on that line.
