### ISSUE TITLE
API to enable or disable diagflow

### ISSUE THREAD

**Issue by mystilleef** [dgagn/diagflow.nvim#13]
Can you provide an API to enable and disable `Dialogflow`? I like to disable diagnostics in `InsertMode` and reenable them in `NormalMode`.

**Comment by dgagn** [comment]
There's a new option called `toggle_event` which does exactly what you need.

```lua
  {
    'dgagn/diagflow.nvim',
    opts = {
      toggle_event = { 'InsertEnter' }, -- this can make it toggle like you want it
    },
  }
```
