### ISSUE TITLE
FR: Add `max_height` option

### ISSUE THREAD

**Issue by chrisgrieser** [dgagn/diagflow.nvim#22]
Some LSP servers give out *really* lengthy diagnostics, e.g. type errors where the types are objects with many properties. For this case, a `max_height` option would be very useful
![Pasted image 2023-07-26 at 23 51 05@2x](https://github.com/dgagn/diagflow.nvim/assets/73286100/8e60bf4b-f364-4e94-9664-699b73d4b9cd)

**Comment by dgagn** [comment]
It is now implemented. You can set a max_height property. By default it is 10, but you can change it to whatever you would like.

**Comment by chrisgrieser** [comment]
thank you <3
