### ISSUE TITLE
Bug: Not properly ignored in Insert Mode

### ISSUE THREAD

**Issue by chrisgrieser** [dgagn/diagflow.nvim#26]
If I understand the docs correctly, setting `toggle_event = { "InsertEnter" }, ` is supposed to disable the output while in Insert Mode?

While that does work some of the time, new diagnostics still pop up in Insert mode. As far as I can tell, that is due to `update_event = { 'DiagnosticChanged' }` which gets triggered a lot during typing in insert mode.

Tbf, I am not even sure I understand correctly what the three `*_event` settings exactly do. `toggle_event` hides the diagnostics, `update_event` updates & shows them? In any case, my goal is to simply hide diagnostics completely while in insert mode, and show them while outside insert mode, and I am not sure how to achieve that behavior. Considering that is a configuration many people would like, I'd say it could make sense to offer that directly as a setting?

**Comment by intrntbrn** [comment]
You need to remove `DiagnosticChanged` from `render_event`.

    toggle_event = { "InsertEnter" },
    render_event = { "CursorMoved" },
    update_event = { "DiagnosticChanged", "BufReadPost" },

**Comment by yifan0414** [comment]
maybe this is better
```
toggle_event = { "InsertEnter", "InsertLeave" }, -- if InsertEnter, can toggle the diagnostics on inserts
```
when i enter insert mode, close it. Then leave insert mode, open it.
