### ISSUE TITLE
[Enhancement] Disable for certain filetypes?

### ISSUE THREAD

**Issue by olimorris** [dgagn/diagflow.nvim#29]
It would be great to have the ability to disable this for certain filetypes. I'd be happy to push through a PR too.

My use case is for when I'm scrolling in Lazy's popup I see the LSP notifications in the top right:

![Screen Shot 2023-09-11 at 19 59 47@2x](https://github.com/dgagn/diagflow.nvim/assets/9512444/28806b70-b335-4cbc-bcec-9a45ad6ed23e)

Being able to do something like:

```lua
enable = function() return vim.bo.filetype ~= "lazy" end
```

**Comment by dgagn** [comment]
You can create a PR. It seems like a good improvement.
