### ISSUE TITLE
Break on whitespace

### ISSUE THREAD

**Issue by BonaBeavis** [dgagn/diagflow.nvim#36]
I think the messages would be more readable when the text is broken on whitespace.

**Comment by dgagn** [comment]
Just to let you know, the plugin is already designed to break text on whitespace. However, this might vary depending on the LSP you're using. Could you share any specific examples where the text isn't breaking as expected?

Always open to more ideas or suggestions for improvement. Thanks a lot for your input

**Comment by BonaBeavis** [comment]
Thanks for the fast answers! But I switched to a native implementation, so this can be closed...

```
function _G.show_diagnostics()
    local mode = vim.fn.mode()
    if mode ~= 'V' and mode ~= 'v' and mode ~= '' then
        local _, winnr = vim.diagnostic.open_float({ source = true })
        if winnr then
            local config = vim.api.nvim_win_get_config(winnr)
            config = vim.tbl_extend('force',config,{
              relative = 'win',
              win = vim.api.nvim_get_current_win(),
              row = 0,
              col = 1,
            })
            vim.api.nvim_win_set_config(winnr,config)
        end
    end
end
vim.cmd [[
  autocmd CursorHold * lua _G.show_diagnostics()
]]
EOF
```
