### ISSUE TITLE
Support for plugins like scrollbar

### ISSUE THREAD

**Issue by mblarsen** [dgagn/diagflow.nvim#9]
Would you consider support scrollbar plugins like `petertriho/nvim-scrollbar`?

See how the `=` from she scroll bar is pushed to the left, ie. both plugins share the same right hand side space.

<img width="713" alt="image" src="https://github.com/dgagn/diagflow.nvim/assets/247048/c06f8fca-d68a-4cb3-8709-c0f6ad04216c">

**Comment by dgagn** [comment]
You can set the padding_right option to 2 and it should work correctly.

<img width="701" alt="Screenshot 2023-07-10 at 8 38 39 PM" src="https://github.com/dgagn/diagflow.nvim/assets/21992952/2c5e6168-1bba-436f-9b7b-60dfd1ea4d2e">

Here is an example config for `lazy.nvim`

 ```lua
 {
    'dgagn/diagflow.nvim',
    opts = {
      padding_right = 2
    },
  }
```
